# This workflow is a pipeline of multiple actions ,it is   triggered  for commits and pull on master branch

name: Building and publishing the Docker image

on:
  # triggered on push and pull_request on master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
         username: ${{ github.ChickenLivesMatter }}
         password: ${{ secrets.STACKOVERGOAT_APT }}
   
  build:
    # run the commands on ubuntu
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: geting the actor
        # getting the environment variable (the pseudo github of the actor)
        run: echo $GITHUB_ACTOR


      # verify that the repository  is under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with maven
        run: mvn clean package

      - name: Building the Docker image
        run: |

    #      echo ${{ secrets.STACKOVERGOAT_APT }} | docker login ghcr.io -u Dev-technique-u --password-stdin
          docker build -t sog/stackovergoat
          docker tag sog/stackovergoat ghcr.io/sog/stackovergoat
          docker push ghcr.io/sog/stackovergoat
